[UI] EVEREST-1039: checkbox storybook
solovevayaroslavna/everest-students-summer-practice pull request #17
Opened 2024-05-04 21:42 UTC by Daninda

https://perconadev.atlassian.net/browse/EVEREST-1039

![image](https://github.com/solovevayaroslavna/everest-students-summer-practice/assets/126169546/7bf5ad7f-d590-459e-b493-45ca5e4437f1)

2024-05-11 09:42 UTC, solovevayaroslavna commented
I suppose it's important to add a bit more content for designers (It will be just easier to understand the component and it's ability)(https://www.figma.com/design/08jGF3GZAUGmazlQtk0UQk/Peak-DS-Kit?node-id=504-1053&t=elC3HC0Q6YqTBJAp-4). We can orient on peak in all storybook tickets.

2024-05-11 09:42 UTC, solovevayaroslavna requested changes
needs more content

2024-05-13 11:05 UTC, X6uddy commented
parameters such as "name", "control", "controllerProps", "checkboxProps", "labelProps" should not be displayed in storyBook in this form
![image](https://github.com/solovevayaroslavna/everest-students-summer-practice/assets/117294450/a59d26c8-1ef6-4283-8370-16070538e85b)

2024-05-13 11:36 UTC, X6uddy submitted a review, later dismissed

2024-06-06 11:12 UTC, solovevayaroslavna commented
@Daninda мы можем сделать эту страничку с несколькими чекбоксами в виде documentation? а сам чекбокс оставить 1 в story

2024-06-15 04:07 UTC, Daninda commented
@solovevayaroslavna 

Updated story:

https://github.com/solovevayaroslavna/everest-students-summer-practice/assets/126169546/9e45119a-4e3c-4e86-bedc-f91b48c2fcb7

2024-06-17 09:34 UTC, solovevayaroslavna commented
perfect work!) We can move to upstream)

2024-06-17 09:34 UTC, solovevayaroslavna approved these changes

2024-06-18 23:15 UTC, closed without merging